/**
 * Attribution for everything shipped inside the binary.
 *
 * Generated by scripts/licences.mjs from what is actually in package.json, so
 * it cannot quietly fall behind the dependency list.
 */
import { useRouter } from 'expo-router';
import { FlatList, Pressable, StyleSheet, Text, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';

import { display, eyebrow, hitSlopTo44, theme } from '../src/theme';

import licences from '../assets/licences.json';

type Licence = { name: string; version: string; licence: string; url: string | null };

export default function Licences() {
  const router = useRouter();
  const insets = useSafeAreaInsets();

  return (
    <View style={[styles.screen, { paddingTop: insets.top + theme.space.md }]}>
      <Pressable
        onPress={() => router.back()}
        accessibilityRole="button"
        accessibilityLabel="Back"
        hitSlop={hitSlopTo44(34)}
        style={styles.back}
      >
        <Text style={styles.backGlyph}>‹</Text>
      </Pressable>

      <Text style={styles.eyebrow}>◆ Open source</Text>
      <Text style={styles.title}>Built on their work.</Text>

      <FlatList
        data={licences as Licence[]}
        keyExtractor={(item) => item.name}
        contentContainerStyle={{ paddingBottom: insets.bottom + theme.space.xl }}
        renderItem={({ item }) => (
          <View style={styles.row}>
            <Text style={styles.name}>{item.name}</Text>
            <Text style={styles.meta}>
              {item.version} · {item.licence}
            </Text>
          </View>
        )}
      />
    </View>
  );
}

const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: theme.color.surface, paddingHorizontal: theme.space.xl },
  back: {
    width: 34,
    height: 34,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: theme.color.border,
    backgroundColor: theme.color.card,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 14,
  },
  backGlyph: { fontSize: 22, lineHeight: 24, color: theme.color.text },
  eyebrow: { ...eyebrow, marginBottom: 6 },
  title: { ...display(26), marginBottom: theme.space.lg },
  row: {
    paddingVertical: 11,
    borderBottomWidth: 1,
    borderBottomColor: theme.color.hairline,
  },
  name: { fontFamily: theme.type.body, fontSize: 14, color: theme.color.text },
  meta: {
    fontFamily: theme.type.mono,
    fontSize: 10,
    letterSpacing: 0.4,
    color: theme.color.faint,
    marginTop: 3,
  },
});
